- name: Deploy only changed files
  shell: powershell
  run: |
    $source = "$env:GITHUB_WORKSPACE"
    $dest   = "C:\BottomLine Technologies, Inc\Create!form"

    if (!(Test-Path $dest)) { New-Item -ItemType Directory -Path $dest | Out-Null }

    robocopy $source $dest /E /XO /R:2 /W:2 `
      /XD ".git" ".github" `
      /XF ".gitignore"

    # Treat Robocopy codes 0-7 as success; 8+ as failure
    $rc = $LASTEXITCODE
    if ($rc -ge 8) { exit $rc } else { exit 0 }


